/**
 * Created by Akhil on 2022-04-07.
 */

public inherited sharing class AccountDomain {

	public void beforeInsert(List<Account> records){

	}

	public void afterInsert(List<Account> records){

	}

	public void beforeUpdate(List<Account> records, Map<Id, Account> oldRecords){

	}

	public void afterUpdate(List<Account> records, Map<Id, Account> oldRecords){

	}

	public void beforeDelete(List<Account> records, Map<Id, Account> oldRecords){

	}

	public void afterDelete(List<Account> records, Map<Id, Account> oldRecords){

	}

	public void afterUndelete(List<Account> records){

	}
}